# Generated by Django 5.2.7 on 2025-10-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kurzcode, z. B. PRAES, GS, VPFIN', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Anzeigename der Verbandsfunktion', max_length=200)),
            ],
            options={
                'verbose_name': 'Verbandsfunktion',
                'verbose_name_plural': 'Verbandsfunktionen',
                'ordering': ['name'],
            },
        ),
    ]
