# Generated by Django 5.2.7 on 2025-10-18 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('GLOBAL', 'Global'), ('PERSOENLICH', 'Persönlicher Bereich'), ('BENUTZER', 'Benutzerverwaltung'), ('KALENDER', 'Vereins/Verbandskalender'), ('RKA', 'Reisekostenantrag'), ('SKE', 'Sachkostenerstattung'), ('HON', 'Honorarabrechnung'), ('BELEG', 'Genehmigung von Belegen'), ('HAUPLAN', 'Haushaltsplanung'), ('FAHRZEUG', 'Verwaltung von Fahrzeugen'), ('ARBEITSZEIT', 'Arbeitszeitdokumentation'), ('ARBEITSURLAUB', 'Arbeits- und Urlaubsplan'), ('DESK', 'Desksharing'), ('SETTINGS', 'Systemeinstellungen')], max_length=32)),
                ('code', models.CharField(help_text='z. B. ANTRAGSTELLER, ANTRAGSBEARBEITER, SYSTEMADMIN', max_length=50)),
                ('name', models.CharField(help_text='Lesbarer Rollenname', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Rolle',
                'verbose_name_plural': 'Rollen',
                'ordering': ['module', 'name'],
                'unique_together': {('module', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ModuleRoleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('GLOBAL', 'Global'), ('PERSOENLICH', 'Persönlicher Bereich'), ('BENUTZER', 'Benutzerverwaltung'), ('KALENDER', 'Vereins/Verbandskalender'), ('RKA', 'Reisekostenantrag'), ('SKE', 'Sachkostenerstattung'), ('HON', 'Honorarabrechnung'), ('BELEG', 'Genehmigung von Belegen'), ('HAUPLAN', 'Haushaltsplanung'), ('FAHRZEUG', 'Verwaltung von Fahrzeugen'), ('ARBEITSZEIT', 'Arbeitszeitdokumentation'), ('ARBEITSURLAUB', 'Arbeits- und Urlaubsplan'), ('DESK', 'Desksharing'), ('SETTINGS', 'Systemeinstellungen')], max_length=32)),
                ('scope_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='iam.role')),
            ],
            options={
                'verbose_name': 'Rollen-Zuweisung',
                'verbose_name_plural': 'Rollen-Zuweisungen',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
