# Generated by Django 5.2.7 on 2025-10-18 13:23

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_holder',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kontoinhaber'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bic',
            field=models.CharField(blank=True, max_length=11, verbose_name='BIC'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='profile',
            name='function_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_func1', to='iam.function'),
        ),
        migrations.AddField(
            model_name='profile',
            name='function_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_func2', to='iam.function'),
        ),
        migrations.AddField(
            model_name='profile',
            name='function_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_func3', to='iam.function'),
        ),
        migrations.AddField(
            model_name='profile',
            name='function_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_func4', to='iam.function'),
        ),
        migrations.AddField(
            model_name='profile',
            name='function_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_func5', to='iam.function'),
        ),
        migrations.AddField(
            model_name='profile',
            name='house_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hausnummer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nachname'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.signature_upload_path, verbose_name='Digitale Unterschrift (JPG/PNG)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Straße'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='PLZ'),
        ),
    ]
