# Generated by Django 5.2.7 on 2025-10-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('year', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CostCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='finance.costcenter')),
            ],
            options={
                'unique_together': {('year', 'code')},
            },
        ),
    ]
