# Generated by Django 5.2.7 on 2025-10-19 07:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_role_moduleroleassignment'),
        ('settingsmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetyear',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='mileagerate',
            options={'ordering': ['km_from']},
        ),
        migrations.AlterField(
            model_name='mileagerate',
            name='km_from',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='ModuleApprovalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('RKA', 'Reisekostenantrag'), ('SKE', 'Sachkostenerstattung'), ('HON', 'Honorarabrechnung'), ('GBL', 'Genehmigung von Belegen')], max_length=4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archive_recipients', models.CharField(help_text='Ablage-E-Mail(s); mehrere durch Semikolon trennen', max_length=1000)),
                ('step2_function', models.ForeignKey(blank=True, help_text='Entscheider Nr. 2 (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_step2_for', to='iam.function')),
                ('step3_function', models.ForeignKey(blank=True, help_text='Entscheider Nr. 3 (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_step3_for', to='iam.function')),
                ('step4_function', models.ForeignKey(blank=True, help_text='Entscheider Nr. 4 (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_step4_for', to='iam.function')),
                ('step5_function', models.ForeignKey(blank=True, help_text='Entscheider Nr. 5 (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_step5_for', to='iam.function')),
            ],
            options={
                'ordering': ['module'],
            },
        ),
    ]
