# Generated by Django 5.2.7 on 2025-11-06 15:23

import apps.refunds.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('iam', '0002_role_moduleroleassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_cluster', models.CharField(blank=True, default='', help_text='Demofeld; echte Verknüpfung auf Modell folgt später.', max_length=120, verbose_name='Cluster')),
                ('receipt_date', models.DateField(verbose_name='Beleg vom')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag (EUR)')),
                ('title', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('reason', models.TextField(blank=True, verbose_name='Begründung')),
                ('receipt', models.FileField(blank=True, null=True, upload_to=apps.refunds.models.refund_receipt_upload_to, verbose_name='Beleg (PDF/JPG)')),
                ('signature_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Unterschrift (Name in Druckschrift)')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=apps.refunds.models.refund_receipt_upload_to, verbose_name='Unterschrift (PNG)')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('returned', 'Zurückgegeben')], default='draft', max_length=20)),
                ('is_factually_correct', models.BooleanField(default=False, verbose_name='sachlich richtig')),
                ('is_mathematically_correct', models.BooleanField(default=False, verbose_name='rechnerisch richtig')),
                ('approver_comment', models.TextField(blank=True, default='', verbose_name='Bemerkungen (Genehmigung)')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
                ('approver_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_first_level', to='iam.function', verbose_name='1. Entscheider (Funktion)')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='finance.costcenter', verbose_name='Kostenstelle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
