# Generated by Django 5.2.7 on 2025-10-19 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0002_role_moduleroleassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('step1_function', models.ForeignKey(help_text='Entscheider Nr. 1 (vom Antragsteller gewählt)', on_delete=django.db.models.deletion.PROTECT, to='iam.function')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
