# Generated by Django 5.2.7 on 2025-10-19 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_role_moduleroleassignment'),
        ('rka', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Entwurf'), ('IN_REVIEW', 'Im Genehmigungsprozess'), ('RETURNED', 'Zur Korrektur zurückgegeben'), ('APPROVED', 'Final genehmigt'), ('REJECTED', 'Abgelehnt')], default='IN_REVIEW', max_length=16),
        ),
        migrations.CreateModel(
            name='ApprovalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='1..n entsprechend der Reihenfolge')),
                ('decision', models.CharField(choices=[('APPROVE', 'Genehmigt'), ('RETURN', 'Zur Korrektur zurückgegeben'), ('REJECT', 'Abgelehnt')], max_length=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iam.function')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rka.travelrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
