# Generated by Django 5.2.7 on 2025-10-26 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_role_moduleroleassignment'),
        ('rka', '0002_travelrequest_status_approvalevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelrequest',
            options={},
        ),
        migrations.RenameField(
            model_name='approvalevent',
            old_name='request',
            new_name='travel_request',
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='approvalevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalevent',
            name='decision',
            field=models.CharField(choices=[('APPROVE', 'Genehmigt'), ('RETURN', 'Zurückgegeben'), ('REJECT', 'Abgelehnt')], max_length=10),
        ),
        migrations.AlterField(
            model_name='approvalevent',
            name='step_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Entwurf'), ('IN_REVIEW', 'Im Genehmigungsprozess'), ('RETURNED', 'Zurückgegeben'), ('APPROVED', 'Vollständig genehmigt'), ('REJECTED', 'Abgelehnt')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='step1_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='iam.function'),
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='rka.travelrequest')),
            ],
        ),
    ]
