# Generated by hand to fix broken defaults on SQLite
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('rka', '0003_alter_travelrequest_options_and_more'),
    ]

    operations = [
        # aus alter 0004: Aufr?umen
        migrations.RemoveField(
            model_name='expenseitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='step1_function',
        ),
        migrations.DeleteModel(
            name='ApprovalEvent',
        ),

        # fehlende Felder mit *string* Defaults (SQLite-sicher)
        migrations.AddField(
            model_name='travelrequest',
            name='origin',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='destination',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='purpose',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='start_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='end_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
