# Generated by Django 5.2.7 on 2025-10-26 18:18

import apps.rka.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('iam', '0002_role_moduleroleassignment'),
        ('rka', '0004_alter_travelrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenseitem',
            options={'ordering': ['date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='travelrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=apps.rka.models.receipt_upload_to, verbose_name='Beleg (PDF/JPG)'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='approver_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rka_first_level', to='iam.function'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.costcenter'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='km_claimed',
            field=models.PositiveIntegerField(default=0, help_text='Vom Antragssteller eingetragene km.', verbose_name='Beantragte km'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='km_deviation_reason',
            field=models.TextField(blank=True, help_text='Pflicht, falls Abweichung > Toleranz.', verbose_name='Begründung Mehrkilometer'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='km_planned',
            field=models.PositiveIntegerField(default=0, help_text='Ergebnis aus Routenplaner.', verbose_name='Geplante km (Routenplaner)'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag (EUR)'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='travel_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rka.travelrequest'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rka_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='Zielort'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='end_date',
            field=models.DateField(verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='end_time',
            field=models.TimeField(verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='origin',
            field=models.CharField(max_length=255, verbose_name='Startort'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='purpose',
            field=models.CharField(max_length=255, verbose_name='Zweck der Reise'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='start_date',
            field=models.DateField(verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='start_time',
            field=models.TimeField(verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='draft', max_length=20),
        ),
    ]
