# Generated by Django 5.2.7 on 2025-11-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rka', '0005_alter_expenseitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='approval_notes',
            field=models.TextField(blank=True, verbose_name='Bemerkungen'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='approval_rechnerisch',
            field=models.BooleanField(default=False, verbose_name='rechnerisch richtig'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='approval_sachlich',
            field=models.BooleanField(default=False, verbose_name='sachlich richtig'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='destination_city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='destination_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='destination_street',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ziel (Ort)'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rückkehr (Datum)'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Rückkehr (Zeit)'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Start (Ort)'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='Reisezweck'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Abfahrt (Datum)'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Abfahrt (Zeit)'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Entwurf'), ('SUBMITTED', 'Eingereicht'), ('IN_REVIEW', 'In Prüfung'), ('APPROVED', 'Genehmigt'), ('REJECTED', 'Abgelehnt'), ('RETURNED', 'Zurückgegeben')], default='DRAFT', max_length=20),
        ),
    ]
