# Generated by Django 5.2.7 on 2025-11-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rka', '0006_travelrequest_approval_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='approval_notes',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='approval_rechnerisch',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='approval_sachlich',
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='Zielort'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='end_date',
            field=models.DateField(verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='origin',
            field=models.CharField(max_length=255, verbose_name='Startort'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Zweck der Reise'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='start_date',
            field=models.DateField(verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('returned', 'Zurückgegeben')], default='draft', max_length=20),
        ),
    ]
